App_Blog/urls.py
from django.urls import path
from App_Blog import views


app_name='App_Blog'

urlpatterns = [
    path('',views.BlogList.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    
    
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name='App_Login'

urlpatterns = [

    path('signup/',views.sing_up,name='signup'),
    path('signin/',views.login_page,name='signin'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('updated-profile/',views.user_change,name='updatedprofile'),
    path('password/',views.pass_change,name='pass_change'),
    path('change-profile-image/',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
    

]

My_Blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('',views.home,name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Blog(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='post_author')
    blog_title= models.CharField(max_length=264,verbose_name='Put a Title')
    slug=models.SlugField(max_length=264,unique=True) #getting the URL as title when click on the post
    blog_content= models.TextField(verbose_name='what is on your mind?')
    blog_image=models.ImageField(upload_to='blog_image',verbose_name="Blog Image")
    publish_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)

    

    class Meta:
        ordering = ['-publish_date']


    def __str__(self):
        return self.blog_title



class Comment(models.Model):
    blog= models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='blog_comment')
    user= models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
    comment=models.TextField()
    comment_date=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date']


    def __str__(self):
        return self.comment



class Likes(models.Model):
    blog=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='liked_blog')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='liker_user')

    

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfile(models.Model):
    user=models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic')

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile

class SignUpForm(UserCreationForm):
    email= forms.EmailField(label='Email Address',required=True)
    
    class Meta:
        model =  User
        fields = ('username','email','password1','password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password')
        
class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic',]

App_Blog/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.views.generic import CreateView,UpdateView,ListView,DetailView,TemplateView,DeleteView
from App_Blog.models import Blog,Comment,Likes
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
import uuid

# Create your views here.

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name='App_Blog/blog_list.html'
    queryset=Blog.objects.order_by('-publish_date')
    
class CreateBlog(LoginRequiredMixin,CreateView):
    model = Blog
    template_name='App_Blog/create_blog.html'
    fields = ('blog_title','blog_content','blog_image',)

    def form_valid(self,form):
        blog_obj = form.save(commit=False)
        blog_obj.author=self.request.user
        title = blog_obj.blog_title
        blog_obj.slug=title.replace(" ","-") + "-"+str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('home'))

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login,logout,authenticate
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm,UserProfileChange,ProfilePic


# Create your views here.

def sing_up(request):
    form = SignUpForm()
    registered = False

    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    dict = {'form':form, 'registered':registered}   
    return render(request,'App_Login/signup.html',context=dict)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user =  authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
    
    return render(request,'App_Login/login.html',context={'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:signin'))


@login_required
def profile(request):
    return render(request,'App_Login/profile.html',context={})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST,instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    return render(request,'App_Login/change_profile.html',context={'form':form})


@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user,data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request,'App_Login/pass_change.html',context={'form':form,'changed':changed})

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST,request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))

    return render(request,'App_Login/pro_pic_add.html',context={'form':form})

@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form= ProfilePic(request.POST,request.FILES,instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request,'App_Login/pro_pic_add.html',context={'form':form})

My_Blog_project/views.py
from django.http import HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse

def home(request):
    return HttpResponseRedirect(reverse('App_Blog:blog_list'))

templates/App_Blog/blog_details.html
{%  extends 'index.html' %}

{% block title %} Blog Details {% endblock %}

{% block body_block %}

<div class="row">
    <div class="col-sm-6">
        <h2>{{ blog.blog_title }}</h2>
         <h6>Posted By : {{ blog.author }}</h6>
         <i><h6>Published On: {{ blog.publish_date }}</h6></i>
         <i><h6>Updated On: {{ blog.update_date }}</h6></i>
    </div>

    <div class="col-sm-6">

        <img src="/media/{{blog.blog_image}}" width="100px">

    </div>
    {{ blog.blog_content|linebreaks }}
    
    
</div>



{% endblock %}

templates/App_Blog/blog_list.html
{%  extends 'index.html' %}

{% block title %} Home {% endblock %}

{% block body_block %}

{% for blog in blogs %}

<h2> {{ blog.blog_title }} </h2>
<h6><i>{{blog.publish_date}}</i></h6>

<div class="row">
    <div class="col-sm-4">

        <img src="/media/{{blog.blog_image}}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="80%">

    </div>

    <div class="col-sm-8">
        <p>
            {{blog.blog_content|truncatechars:255|linebreaks }}
        </p>
        <h6>Posted By: <a href="">{{blog.author}}</a></h6>

    </div>

</div>


{% endfor %}

{% endblock %}

templates/App_Blog/create_blog.html
{%  extends 'index.html' %}
{% load crispy_forms_tags %}
{% block title %} Create Blog {% endblock %}

{% block body_block %}

<h2>Write the blog here:</h2>

<form method="post" enctype="multipart/form-data">

    {{ form|crispy }}
    {% csrf_token %}

    <button type="submit" class="btn btn-success btn-sm">
        Publish
    </button>
</form>
<br><br><br>

    {% endblock %}

templates/App_Blog/edit_blog.html
{%  extends 'index.html' %}

{% block title %} Edit Blog {% endblock %}

{% block body_block %}



    {% endblock %}

templates/App_Blog/my_blogs.html
{%  extends 'index.html' %}

{% block title %} My Blog {% endblock %}

{% block body_block %}



    {% endblock %}

templates/App_Login/change_profile.html
{%  extends 'index.html' %}
{% load crispy_forms_tags %}
{% block title %} Changed User Profile {% endblock %}


{% block body_block %}

<h2>Updated User Profile</h2>

<form method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">
        Update
    </button>
</form>


{% endblock %}

templates/App_Login/login.html
{%  extends 'index.html' %}
{% load crispy_forms_tags %}
{% block title %} Login Page {% endblock %}


{% block body_block %}

<h2>Login to your Accont</h2>

<form method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">
        Login
    </button>
</form>


{% endblock %}

templates/App_Login/pass_change.html
{%  extends 'index.html' %}
{% load crispy_forms_tags %}
{% block title %} Password Change Page {% endblock %}


{% block body_block %}

{% if changed %}

<div class="alert alert-success">
    Password changed successfully.<a href="{% url 'App_Login:signin' %}">Login Here</a>
</div>

{% endif %}

<h2>Password Change</h2>

<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">
        Change
    </button>
</form>


{% endblock %}

templates/App_Login/pro_pic_add.html
{%  extends 'index.html' %}
{% load crispy_forms_tags %}
{% block title %} Profile Picture {% endblock %}


{% block body_block %}

<h2>Profile Picture Update</h2>

<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">
        Add Picture
    </button>
</form>


{% endblock %}

templates/App_Login/profile.html
{%  extends 'index.html' %}

{% block title %} Profile Page {% endblock %}


{% block body_block %}

<h2>Welcome to your Profile</h2>

{% if user.user_profile %}

<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="150px">
<br><br>
<a href="{% url 'App_Login:change_pro_pic' %}" class="btm btn-info btn-sm">Change Profile Image</a>

{% else %}

<img src="/media/download.jfif" class="rounded-circle" width="150px">
<br>
<br>
<a href="{% url 'App_Login:add_pro_pic' %}" class="btm btn-info btn-sm">Change Profile Image</a>
<br>
{% endif %}


<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name: {{ user.first_name }} {{ user.last_name }} </p>

<br>

<a href="{% url 'App_Login:updatedprofile' %}" class="btn btn-warning btn-sm">Updated Profile Info</a>


{% endblock %}

templates/App_Login/signup.html
{%  extends 'index.html' %}
{% load crispy_forms_tags %}
{% block title %} Create New Account {% endblock %}

{% block body_block %}

{% if registered %}

<div class="alert alert success">
    Account created successfully <a href="{% url 'App_Login:signin' %}">Login Here</a>
</div>
{% else %}

<h2>Create new account</h2> 

<form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>

<p>
    Already have an account ? <a href="{% url 'App_Login:signin' %}">Login here</a>
</p>

{% endif %}

    {% endblock %}

templates/index.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>
        {% block title %}

        Blogs Page

        {% endblock %}
    </title>
</head>

<body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

        <ul class="navbar-nav">

            <li class="navbar-item active">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>

            {% if user.is_authenticated %}

            <li class="navbar-item active">
                <a class="nav-link" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>
            </li>

            <li class="navbar-item active">
                <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
            </li>
            <li class="navbar-item active">
                <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
            </li>

            {% else %}

            <li class="navbar-item active">
                <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
            </li>
            <li class="navbar-item active">
                <a class="nav-link" href="{% url 'App_Login:signin' %}">Login</a>
            </li>

            {% endif %}
        </ul>

        {% if user.is_authenticated %}

        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                {{ user.username }}
            </a>

            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
                <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                
              </div>
        </div>
        {% endif %}

    </nav>

    <div class="container" style="padding-top: 25px;">

        {% block body_block %}

        {% endblock %}

    </div>














    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>